name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, sqlite
        coverage: none

    - name: Install Dependencies
      run: |
        composer install --ignore-platform-reqs
        npm install
        npm run build

    - name: Set Up SQLite Database
      run: |
        touch database/database.sqlite

    - name: Run Migrations
      run: |
        cp .env.testing .env
        php artisan key:generate
        php artisan migrate

    # Start Laravel server in the background
    - name: Start Laravel Server
      run: |
        php artisan serve --host=127.0.0.1 --port=8000 &  
        sleep 5  # Give the server time to start

    - name: Run Tests
      run: |
        php artisan test
